import classNames from 'classnames';

/******************************************************************
 *
 *  THIS COMPONENT WAS GENERATED BY NEXTCRAZY-CLI
 *
 ******************************************************************/

type LabelProps = {
   label?: React.ReactNode | string;
   isRequired?: boolean;
   id: string;
};

const Label = ({ label, isRequired, id }: LabelProps) => {
   return (
      <label
         htmlFor={id}
         className={classNames('mb-1 inline-block text-gray-400', isRequired && 'required-label')}>
         {label}
      </label>
   );
};

export default Label;
