import { Translate } from '~/i18n';
import Image from '../shared/image';
import { marketCategories } from '~/data/marketing-categories';
/******************************************************************
 *
 *  THIS COMPONENT WAS GENERATED BY NEXTCRAZY-CLI
 *
 ******************************************************************/

const ExhibitionMarket = () => {
   // const { lang } = useTranslate();

   return (
      <div className='bg-exhibition-market bg-cover bg-center bg-no-repeat'>
         <section className="container pb-32">
            <div className="row">
               <div className="xl:col-10 xl:offset-1">
                  <div className=" mb-16">
                     <h2 className="text-[40px] sm:text-[50px] font-bold text-[#c28c24] uppercase leading-tight">
                        <Translate id="web:one_stop_exhibition" />
                     </h2>
                     <h3 className="text-[30px] sm:text-[40px] text-[#c28c24] uppercase mt-2">
                        <Translate id="web:new_market_access" />
                     </h3>
                     <p className="mt-8 text-white text-lg max-w-4xl">
                        <span className="font-bold">EDGEx</span>
                        <Translate id="web:exhibition_description" />
                     </p>
                  </div>

                  <div className="row">
                     {marketCategories.map((category, index) => (
                        <div key={index} className="col-12 md:col-6 lg:col-3 mb-6">
                           <div className="bg-[#0a0a0a] rounded-lg p-8 text-center border border-gray-800 hover:border-[#c28c24] transition-colors duration-300 h-full relative">
                              <div className="h-16 w-16 mx-auto mb-4">
                                 <Image
                                    src={`/images/icons/${category.icon}.svg`}
                                    alt={category.title}
                                    width={64}
                                    height={64}
                                    layout="responsive"
                                    className="filter invert opacity-80"
                                 />
                              </div>
                              <h4 className="text-white text-lg font-medium">
                                 <Translate id={`web:${category.title}`} />
                              </h4>
                              <div className="absolute bottom-0 translate-y-1/2 left-0 right-0">
                                 <Image
                                    src="/images/horizontal_line.png"
                                    alt="horizontal line"
                                    width={100}
                                    height={5}
                                    layout="responsive"
                                    className="w-full"
                                 />
                              </div>
                           </div>
                        </div>
                     ))}
                  </div>
               </div>
            </div>
         </section>
      </div>
   );
};

export default ExhibitionMarket;
