import classNames from 'classnames';
// import Image from '../shared/image';
import { Translate, useTranslate } from '~/i18n';

import { Icon } from '@iconify/react';
import React from 'react';
// import Image from '../shared/image';
// import Image from '../shared/image';

/******************************************************************
 *
 *  THIS COMPONENT WAS GENERATED BY NEXTCRAZY-CLI
 *
 ******************************************************************/

const HeroSection = () => {
   const { lang } = useTranslate();
   return (
      <div>
         <div className="h-[700px] bg-hero-sm bg-cover bg-center bg-no-repeat   md:h-[800px] ltr:md:bg-hero rtl:md:bg-hero-rtl lg:h-[850px]">
            <section className="container relative flex h-full flex-col justify-center">
               <div className="row">
                  <div className="col-12">
                     <div className="sm:px-10">
                        <h1>
                           {lang === 'en' ? (
                              <React.Fragment>
                                 <div
                                    className={classNames(
                                       'text-white',
                                       'font-medium',
                                       'text-[40px] sm:text-[50px] md:text-[58px] lg:text-[70px] xl:text-[85px]',
                                       'leading-none',
                                       'bg-clip-text text-transparent',
                                       'font-29ltbukra'
                                       // 'ltr:custom-gradient rtl:bg-gradient-to-l' // Replace or extend with a custom gradient class
                                    )}
                                    style={{
                                       backgroundImage:
                                          'linear-gradient(180deg, #a0a0a0, #ffffff, #ffffff)',
                                    }}>
                                    Beyond
                                 </div>
                                 <div
                                    className={classNames(
                                       'text-white',
                                       'font-medium',
                                       'text-[40px] sm:text-[50px] md:text-[58px] lg:text-[70px] xl:text-[85px]',
                                       'leading-none',
                                       'bg-clip-text text-transparent',
                                       'font-29ltbukra'
                                       // 'ltr:custom-gradient rtl:bg-gradient-to-l' // Replace or extend with a custom gradient class
                                    )}
                                    style={{
                                       backgroundImage:
                                          'linear-gradient(180deg, #a0a0a0, #ffffff, #ffffff)',
                                    }}>
                                    Readiness
                                 </div>
                              </React.Fragment>
                           ) : (
                              <React.Fragment>
                                 <div
                                    className={classNames(
                                       'text-white',
                                       'font-semibold',
                                       'text-[40px] sm:text-[50px] md:text-[58px] lg:text-[70px] xl:text-[85px]',
                                       'leading-tight',
                                       'bg-clip-text text-transparent'
                                       // 'ltr:custom-gradient rtl:bg-gradient-to-l' // Replace or extend with a custom gradient class
                                    )}
                                    style={{
                                       backgroundImage:
                                          'linear-gradient(180deg, #a0a0a0, #ffffff, #ffffff)',
                                    }}>
                                    ما بعد الاستعداد
                                 </div>
                                 <div
                                    className={classNames(
                                       'text-white',
                                       'font-semibold',
                                       'text-[40px] sm:text-[50px] md:text-[58px] lg:text-[70px] xl:text-[85px]',
                                       'leading-tight',
                                       'bg-clip-text text-transparent'
                                       // 'ltr:custom-gradient rtl:bg-gradient-to-l' // Replace or extend with a custom gradient class
                                    )}
                                    style={{
                                       backgroundImage:
                                          'linear-gradient(180deg, #a0a0a0, #ffffff, #ffffff)',
                                    }}>
                                    للمستقبل
                                 </div>
                              </React.Fragment>
                           )}
                        </h1>

                        <div className={classNames(
                           'mt-4',
                           'font-ar',
                           'font-medium'
                        )}>
                           <p className="text-xl text-[#c28c24]">
                              <Translate id="web:event_date_location" />
                           </p>
                        </div>

                        <div className="mt-14">
                           <p className="text mb-3 text-white font-ar">
                              <Translate id="web:hero_p1" />
                           </p>
                           <hr className="w-[200px]"></hr>
                           <div className="row">
                              <div className="lg:col-5">
                                 <p className="mt-4 text-sm text-gray-400 font-ar">
                                    <Translate id="web:hero_p2" />
                                 </p>
                              </div>
                           </div>
                        </div>

                        <div className="row mt-5">
                           <div className="md:col-6 lg:col-4">
                              <a
                                 target="_blank"
                                 rel="noopener noreferrer"
                                 className={classNames(
                                    'block bg-emerald-500 px-6 py-2 text-xl font-ar font-semibold uppercase text-black md:text-2xl relative',
                                    'focus:border-accent focus:ring-accent focus:outline-none focus:ring focus:ring-opacity-50'
                                 )}
                                 href={`https://registration.humancapabilityinitiative.org/${lang}/join/public-delegate`}
                                 style={{
                                    clipPath: lang === 'en'
                                       ? 'polygon(0% 0%, 95% 0%, 100% 30%, 100% 100%, 0% 100%)'
                                       : 'polygon(100% 0%, 10% 0%, 0% 50%, 0% 100%, 100% 100%)'
                                 }}>
                                 <span className="flex items-center justify-between">
                                    <span className="flex-grow">
                                       <Translate id="web:attend_now" />
                                    </span>
                                    <span>
                                       {lang === 'en' ? (
                                          <Icon icon="fa:chevron-right" className="h-[20px] w-[20px]" />
                                       ) : (
                                          <Icon icon="fa:chevron-left" className="h-[20px] w-[20px]" />
                                       )}
                                    </span>
                                 </span>
                              </a>

                           </div>
                        </div>

                        {/* <div>
                           <p className="text  mt-10 text-white">
                              <Translate id="web:in_claboration_with" />
                           </p>
                           <div>
                              <div className="h-[70px] w-[340px]">
                                 <Image
                                    src={`/images/in_collaboration_with_${lang}_4.png`}
                                    alt="logos"
                                    // width="150"
                                    // height="71"
                                    layout="fill"
                                    objectFit="contain"
                                    className="rounded-lg"
                                 />
                              </div>
                           </div>
                        </div> */}


                        {/* Added tagline */}
                        {/* <div className="text-center my-28">
                           <h2 className="text-white text-[32px] md:text-[40px] font-29ltbukra font-medium leading-[60px]">
                              Bringing the world of education<br />
                              together to revolutionise the future
                           </h2>
                        </div> */}
                     </div>
                  </div>
               </div>
            </section>
         </div>
         {/* Added tagline */}
         <div className=" -mt-[100px] mb-40">
            <div className="-mt-[100px] "
               style={{
                  background: "linear-gradient(172.4deg, #00465C 0%, #00ABA6 100%)"
               }}>
               <div className='container'>
                  <div className="py-10">
                     <div className="row">
                        {/* Visitors */}
                        <div className='md:col-3'>
                           <div className="text-center text-white">
                              <div className="text-[52px] font-medium">20,000</div>
                              <div className="mt-2 text-[24px] font-regular">
                                 <Translate id="web:visitors" />
                              </div>
                           </div>
                        </div>
                        <div className='md:col-3'>
                           {/* Exhibitors */}
                           <div className="text-center text-white">
                              <div className="text-[52px] font-medium">100+</div>
                              <div className="mt-2 text-[24px] font-regular">
                                 <Translate id="web:exhibitors" />
                              </div>
                           </div>
                        </div>
                        <div className='md:col-3'>
                           {/* Speakers */}
                           <div className="text-center text-white">
                              <div className="text-[52px] font-medium">50+</div>
                              <div className="mt-2 text-[24px] font-regular">
                                 <Translate id="web:speakers" />
                              </div>
                           </div>
                        </div>
                        <div className='md:col-3'>

                           {/* SQM Space */}
                           <div className="text-center text-white">
                              <div className="text-[52px] font-medium">8,700</div>
                              <div className="mt-2 text-[24px] font-regular">
                                 <Translate id="web:sqm_space" />
                              </div>
                           </div>
                        </div>





                     </div>

                  </div>
               </div>

            </div>
         </div>
      </div>
   );
};

export default HeroSection;
