import React from 'react';
import HeroSection from './hero-section';
import OverviewSection from './overview-section';
import TogetherSection from './together-section';
import TransformingSection from './transforming-section';
import WhySection from './why-section';
import ContactUsSection from './contact-us-section';
import ExhibitionMarket from './exhibition-market';
import QuotationSection from './quotation-section';
import OpportunitiesSection from './opportunities-section';

/******************************************************************
 *
 *  THIS COMPONENT WAS GENERATED BY NEXTCRAZY-CLI
 *
 ******************************************************************/

const HomepageSections = () => {
   // Cookies.remove('reg_num');

   return (
      <React.Fragment>
         <HeroSection />

         <OverviewSection />
         <TogetherSection />
         <TransformingSection />
         <ExhibitionMarket />
         <OpportunitiesSection />
         <QuotationSection />
         <WhySection />
         <ContactUsSection />
      </React.Fragment>
   );
};

export default HomepageSections;
