import { Translate, useTranslate } from '~/i18n';
import Image from '../shared/image';
// import classNames from 'classnames';

/******************************************************************
 *
 *  THIS COMPONENT WAS GENERATED BY NEXTCRAZY-CLI
 *
 ******************************************************************/

const OpportunitiesSection = () => {
   const { lang } = useTranslate();
   const immersiveExpoDetails = [
      {
         card_poster: '/images/overview/_1.png',
         title_en: 'EDGE TECH UNLEASH EXPLOSIVE GROWTH',
         title_ar: 'حلول التعلّم التفاعلي',
         desc_en:
            'Demonstrate your commitment to innovative education and capture the interest of thousands of educators, investors, and decision-makers.',
         desc_ar:
            'خبراء التعليم ومبتكرو التقنيات أنجح الحلول التعليمية الرقمية، وأحدث أساليب الإشراف والإرشاد الأكاديمي، لهيئة التعليم وكافة المستفيدين من العملية التعليمية.',
      },
      {
         card_poster: '/images/overview/_2.png',
         title_en: 'FORGE STRATEGIC PARTNERSHIPS',
         title_ar: 'ورش عمل تفاعلية',
         desc_en:
            'Collaborate with key players in the KSA education ecosystem and secure long-term business development opportunities.',
         desc_ar:
            'فرص واعدة لمواكبة مهارات المستقبل التقنية، وتبادل الخبرات، والشركات الاستراتيجية نحو أدوات الذكاء الاصطناعي والواقع المعزز.',
      },
      // {
      //    card_poster: '/images/overview/3.jpg',
      //    title_en: 'FUNDRAISING EVENT',
      //    title_ar: 'حدث لجمع التبرعات',
      //    desc_en: 'A 3D mapping immersive experience of the lifelong educational journey.',
      //    desc_ar: 'تجربة غامرة ثلاثية الأبعاد لرحلة تعليمية مدى الحياة.',
      // },
      {
         card_poster: '/images/overview/_3.png',
         title_en: 'SHOWCASE YOUR INNOVATION',
         title_ar: 'رحلة التعليم',
         desc_en: 'Engage visitors with dynamic product demonstrations, interactive experiences, and live technology showcases.',
         desc_ar: 'استكشف أساليب التعلّم مدى الحياة في ضوء آخر مستجدات التقنية والذكاء الاصطناعي.',
      },
      {
         card_poster: '/images/overview/_4.png',
         title_en: 'ALIGN WITH THE FUTURE',
         title_ar: 'تجربة مختلفة',
         desc_en:
            'Be part of an event that supports the Kingdom’s vision for education and human capability development—empowering growth, transformation, and a sustainable future.',
         desc_ar: 'معرض مصمم بأساليب مبتكرة لتقديم تجربة جاذبه مصممة للإلهام وخلق انطباعات دائمة.',
      },
   ];

   return (
      <section className="container lg:mt-[50px]" id="overview">
         <div className=" lg:col-10 lg:offset-1">
            <h1 className="text-4xl font-bold text-teal-400 leading-tight">
               <Translate id="web:limitless_opportunities" />
            </h1>
            <h2 className="text-2xl font-normal text-teal-400 leading-snug">
               <Translate id="web:for_your_brand" />
            </h2>
         </div>
         <div className="row">
            <div className="lg:col-10 lg:offset-1">
               <div className="row mt-24 justify-center">
                  {
                     /* <!-- Card --> */
                     immersiveExpoDetails.map((item, index) => (
                        <div key={index} className="mb-20 md:col-6">
                           <div className="relative h-full border border-gray-800 bg-[#171717] md:mx-5">
                              <div className="relative block h-[250px] w-full">
                                 <Image
                                    src={item.card_poster}
                                    alt="bg_overview"
                                    layout="fill"
                                    objectFit="cover"
                                    className="opacity-50"
                                 />
                                 <div className="absolute inset-x-0 bottom-0 p-5">
                                    <h3 className="text-[20px] font-bold italic text-white">
                                       {lang === 'en' ? item.title_en : item.title_ar}
                                    </h3>
                                 </div>
                              </div>
                              <div className="mb-20 p-5">
                                 <p className="mt-3 text-lg text-gray-400">
                                    {lang === 'en' ? item.desc_en : item.desc_ar}
                                 </p>
                              </div>
                              <div className="absolute inset-x-0 -bottom-4 -z-10 bg-black text-center">
                                 <img
                                    src="/images/bottom-light.png"
                                    alt=""
                                    className="relative z-10 block"
                                 />
                              </div>
                           </div>
                        </div>
                     ))
                  }
               </div>
            </div>
         </div>
      </section>
   );
};

export default OpportunitiesSection;
