import { Translate, useTranslate } from '~/i18n';
import Image from '../shared/image';
// import classNames from 'classnames';

/******************************************************************
 *
 *  THIS COMPONENT WAS GENERATED BY NEXTCRAZY-CLI
 *
 ******************************************************************/

const OverviewSection = () => {
   const { lang } = useTranslate();
   const immersiveExpoDetails = [
      {
         card_poster: '/images/overview/_1.jpg',
         title_en: 'EDGE TECH',
         title_ar: 'حلول التعلّم التفاعلي',
         desc_en:
            'An Immersive exhibition connecting education professionals with the latest innovations, plus an experiential showcase for parents and students with gamified learning and university guidance.',
         desc_ar:
            'خبراء التعليم ومبتكرو التقنيات أنجح الحلول التعليمية الرقمية، وأحدث أساليب الإشراف والإرشاد الأكاديمي، لهيئة التعليم وكافة المستفيدين من العملية التعليمية.',
      },
      {
         card_poster: '/images/overview/_2.jpg',
         title_en: 'WORKSHOPS',
         title_ar: 'ورش عمل تفاعلية',
         desc_en:
            'Interactive sessions aimed at fostering knowledge exchange and skill development across diverse educational topics.',
         desc_ar:
            'فرص واعدة لمواكبة مهارات المستقبل التقنية، وتبادل الخبرات، والشركات الاستراتيجية نحو أدوات الذكاء الاصطناعي والواقع المعزز.',
      },
      // {
      //    card_poster: '/images/overview/3.jpg',
      //    title_en: 'FUNDRAISING EVENT',
      //    title_ar: 'حدث لجمع التبرعات',
      //    desc_en: 'A 3D mapping immersive experience of the lifelong educational journey.',
      //    desc_ar: 'تجربة غامرة ثلاثية الأبعاد لرحلة تعليمية مدى الحياة.',
      // },
      {
         card_poster: '/images/overview/_3.jpg',
         title_en: 'IMMERSIVE EXPERIENCE FOR THE CONTINUOUS EDUCATION JOURNEY',
         title_ar: 'رحلة التعليم',
         desc_en: 'A 3D mapping immersive experience of the life long educational journey.',
         desc_ar: 'استكشف أساليب التعلّم مدى الحياة في ضوء آخر مستجدات التقنية والذكاء الاصطناعي.',
      },
      {
         card_poster: '/images/overview/_4.jpg',
         title_en: 'WOW FACTOR',
         title_ar: 'تجربة مختلفة',
         desc_en:
            'An initiative dedicated to raising support for programs and resources that will drive future educational advancement.',
         desc_ar: 'معرض مصمم بأساليب مبتكرة لتقديم تجربة جاذبه مصممة للإلهام وخلق انطباعات دائمة.',
      },
   ];
   return (
      <section className="container lg:mt-[50px]" id="overview">
         <div className="row">
            <div className="lg:col-6">
               <div className="relative">
                  <div className="block h-[250px] w-full overflow-hidden rounded-md sm:h-[350px] md:h-[400px]">
                     <Image
                        src={`/images/overview_2.png`}
                        alt="bg_overview"
                        layout="fill"
                        objectFit="cover"
                        className="rounded-lg"
                     />
                     <div className="absolute top-0 left-[100%] -translate-x-1/2 h-full w-[5%]">
                        <Image
                           src="/images/overview_2_shadow.png"
                           alt="bg_overview_shadow"
                           layout="fill"
                           objectFit="cover"
                           priority
                        />
                     </div>
                  </div>

                  {lang === 'en' ? (
                     <div className="absolute inset-x-0 text-center xl:bottom-0">
                        <h2 className="text-[50px] sm:text-[72px] md:text-[72px] lg:text-[72px] xl:text-[82px] font-bold text-white leading-[0px]">
                           <span className="font-semibold text-transparent" style={{
                              WebkitTextStroke: '1px white',
                              WebkitTextFillColor: 'transparent',
                           }}>
                              OVER
                           </span>
                           <span className="text-white">VIEW</span>
                        </h2>
                     </div>
                  ) : (
                     <div className="absolute inset-x-0  -bottom-4 text-center  md:-bottom-8 xl:-bottom-8">
                        <div className="mx-auto   h-[40px]   w-[280px] md:h-[60px]  md:w-[500px] lg:h-[60px] lg:w-[500px]  xl:h-[70px] xl:w-[550px]  ">
                           <Image
                              src="/images/overview_ar.png"
                              alt="Education Global Exhibition logo"
                              layout="fill"
                              objectFit="contain"
                              className=""
                           />
                        </div>
                     </div>
                  )}
               </div>
            </div>
            <div className="self-center lg:col-6">
               <p className="mt-10 text-white md:mt-20 md:text-xl lg:mt-0">
                  <Translate id="web:overview_section_description" />
               </p>
            </div>
         </div>
         <div className="row">
            <div className="lg:col-10 lg:offset-1">
               <div className="row mt-40 justify-center">
                  {
                     /* <!-- Card --> */
                     immersiveExpoDetails.map((item, index) => (
                        <div key={index} className="mb-20  md:col-6  ">
                           <div className="relative h-full border border-gray-800 bg-[#171717] md:mx-5">
                              <div className="relative block h-[250px] w-full">
                                 <Image
                                    src={item.card_poster}
                                    alt="bg_overview"
                                    // width="150"
                                    // height="71"
                                    layout="fill"
                                    objectFit="cover"
                                    className=" "
                                 />
                                 <div className="absolute inset-x-0 bottom-0 p-5">
                                    <h3 className="text-[20px] font-bold italic text-white">
                                       {lang === 'en' ? item.title_en : item.title_ar}
                                    </h3>
                                 </div>
                              </div>
                              <div className="mb-20 p-5">
                                 <p className="mt-3 text-lg text-gray-400">
                                    {lang === 'en' ? item.desc_en : item.desc_ar}
                                 </p>
                              </div>
                              <div className="absolute inset-x-0   -bottom-4 -z-10 bg-black  text-center">
                                 <img
                                    src="/images/bottom-light.png"
                                    alt=""
                                    className="relative z-10 block"
                                 />
                              </div>
                           </div>
                        </div>
                     ))
                  }
               </div>
            </div>
         </div>
      </section>
   );
};

export default OverviewSection;
