// import { Translate } from '~/i18n';
// import { useAuth } from '~/auth';
import Image from '../shared/image';
/******************************************************************
 *
 *  THIS COMPONENT WAS GENERATED BY NEXTCRAZY-CLI
 *
 ******************************************************************/

const QuotationSection = () => {
   // const { authenticated } = useAuth();

   return (
      <section>
         <div>
            <div>
               <div className="relative">
                  <div className="h-[600px] w-full">
                     <Image
                        src="/images/circle_with_asset.png"
                        alt="Circle with asset"
                        layout="fill"
                        objectFit="contain"
                        priority
                     />
                  </div>

               </div>
            </div>
         </div>
      </section>
   );
};

export default QuotationSection;
