import { Translate } from '~/i18n';

import Image from '../shared/image';

/******************************************************************
 *
 *  THIS COMPONENT WAS GENERATED BY NEXTCRAZY-CLI
 *
 ******************************************************************/

const TogetherSection = () => {
   return (
      <div className="my-10 h-[650px] bg-together-sm bg-cover bg-top  bg-no-repeat ltr:lg:bg-together rtl:lg:bg-together-ltr">
         <section className="container py-32">
            <div className="row justify-end">
               <div className="lg:col-6 xl:col-5">
                  <div className="text-center">
                     <h2 className="font-ar text-[60px] uppercase leading-none text-white sm:text-[70px]">
                        {/* <Translate id="together" /> */}
                        <div className="font-semibold">
                           <Translate id="web:together" />
                        </div>
                        <div className="font-semibold">
                           <Translate id="web:we_shape" />
                        </div>
                        <div
                           style={
                              {
                                 // WebkitTextStroke: '2px white',
                                 // WebkitTextFillColor: 'transparent',
                              }
                           }
                           className="mt-3 inline-block bg-black p-2 px-10 text-[46px] font-black ltr:tracking-wider sm:text-[55px]">
                           <Translate id="web:the_future" />
                        </div>
                     </h2>
                     <p className="mt-4 text-[27px] font-medium leading-none text-[#00504E]">
                        <Translate id="web:we_are_beyond_readiness" />
                     </p>
                     <div className="mx-auto mt-10 h-[100px] w-[200px]">
                        <Image
                           src="/images/edge_logo_white_v2.png"
                           alt="Education Global Exhibition logo"
                           layout="fill"
                           objectFit="contain"
                           className=""
                        />
                     </div>
                  </div>
               </div>
            </div>
         </section>
      </div>
   );
};

export default TogetherSection;
