import { Translate } from '~/i18n';
// import { useAuth } from '~/auth';
// import classNames from 'classnames';
// import { Icon } from '@iconify/react';

/******************************************************************
 *
 *  THIS COMPONENT WAS GENERATED BY NEXTCRAZY-CLI
 *
 ******************************************************************/

const WhySection = () => {
   return (
      <section className="container pb-32">
         <div className="row">
            <div className="xl:col-10 xl:offset-1">
               <div className="row">
                  <div className="md:col-12">
                     <p className="mt-4 text-lg font-semibold text-gray-300">
                        <Translate id={'web:dominate_saudi_education_market'} />
                     </p>
                     <h2 className="my-8 text-5xl font-medium text-[#059592]">
                        <Translate id={'web:why_exhibit'} />
                     </h2>
                     <p className="mt-4 text-sm text-white">
                        <Translate id={'web:unleash_explosive_growth'} />
                     </p>
                     <hr className="my-4" />
                     <p className="mt-4 text-sm text-white">
                        <Translate id={'web:forge_strategic_partnerships'} />
                     </p>
                     <hr className="my-4" />
                     <p className="mt-4 text-sm text-white">
                        <Translate id={'web:showcase_your_innovation'} />
                     </p>
                     <hr className="my-4" />
                     <p className="mt-4 text-sm text-white">
                        <Translate id={'web:gain_market_intelligence'} />
                     </p>
                     <hr className="my-4" />
                  </div>
               </div>
            </div>
         </div>
      </section>
   );
};

export default WhySection;
