import { NextLink, Translate } from '~/i18n';

import Lottie from 'react-lottie';
import TicAnimations from '~/animations/tic_new.json';
import Cookies from 'js-cookie';
// import classNames from 'classnames';
// import ShareBtnSections from './sharebtn-sections';
// import Cookies from 'js-cookie';
// import { nanoid } from 'nanoid';

/******************************************************************
 *
 *  THIS COMPONENT WAS GENERATED BY NEXTCRAZY-CLI
 *
 ******************************************************************/

type SuccessSectionsProps = {
   // category: string;
   visibility?: 'private' | 'public';
   // withToken: boolean;
};

const SuccessSections = ({ visibility }: SuccessSectionsProps) => {
   Cookies.remove('user_data');
   const regId = Cookies.get('reg_num');
   // console.log(token, 'token');

   return (
      <section>
         <div className="container mb-10 py-5">
            <div className="row">
               <div className="lg:col-6 lg:offset-3">
                  <div className="rounded-lg border bg-white shadow-[0px_7px_29px_0px_rgba(100,100,111,0.2)]">
                     <div className="p-6 sm:p-12">
                        <div className="text-center">
                           <div className="lottie-fix mx-auto h-60 w-60 cursor-default ">
                              <Lottie
                                 options={{
                                    animationData: TicAnimations,
                                    autoplay: true,
                                    loop: false,
                                 }}
                              />
                           </div>
                           <div className="relative z-10">
                              <h1 className=" text-3xl font-bold text-gray-700">
                                 <Translate id="web:thank_you" />
                              </h1>
                              {visibility === 'private' ? (
                                 <p className="mt-2 text-black">
                                    <Translate id="web:thank_you_private" />
                                 </p>
                              ) : (
                                 <p className="mt-2 text-black">
                                    <Translate id="web:thank_you_public" />
                                 </p>
                              )}

                              <div className="mt-4  text-xl font-bold text-gray-700">
                                 <Translate id="web:registration_number" />
                              </div>
                              <div className="font">{regId}</div>
                              <div className="mt-8 text-center">
                                 <NextLink
                                    href={''}
                                    className={
                                       'inline-block bg-secondary px-10 py-4 text-center text-xl font-medium leading-5 text-white transition-colors duration-150 hover:bg-secondary-600 focus:outline-none  active:bg-secondary'
                                    }>
                                    <Translate id="web:back_to_homepage" />
                                 </NextLink>
                              </div>
                              {/* <div className="mt-8">
                                 <hr />
                                 <ShareBtnSections />
                              </div> */}
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </section>
   );
};

export default SuccessSections;
